//@version=6
strategy("Signaux Rapides Achat/Vente", shorttitle="FastSignal", overlay=true, pyramiding=0)

// Paramètres
fastLength = input.int(10, title="Longueur Rapide")
slowLength = input.int(20, title="Longueur Lente")

// Calcul des moyennes mobiles
fastMA = ta.sma(close, fastLength)
slowMA = ta.sma(close, slowLength)

// Conditions de croisement
buySignal = ta.crossover(fastMA, slowMA)
sellSignal = ta.crossunder(fastMA, slowMA)

// Tracer les moyennes mobiles
plot(fastMA, color=color.blue, title="Moyenne Rapide")
plot(slowMA, color=color.red, title="Moyenne Lente")

// Afficher les signaux sur le graphique
plotshape(buySignal, title="Signal Achat", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(sellSignal, title="Signal Vente", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

// Helpers compatibles v6
f_join(arr) =>
    _n = array.size(arr)
    _s = ""
    if _n > 0
        for i = 0 to _n - 1
            _s += (i == 0 ? "" : ",") + array.get(arr, i)
    _s

pc_symbol       = syminfo.ticker
magic_ea        = 202220001
key_ea          = "WebhookReceivedMtOrder:0ea2fe"

// Exécution des ordres
if buySignal
    var string longMsg  = ""
    longOthers  = array.new_string()
    array.push(longOthers, "magic=" + str.tostring(magic_ea))
    array.push(longOthers, "key=" + key_ea)
    array.push(longOthers, "symbol=" + pc_symbol)
    array.push(longOthers, "order_type=buy")
    array.push(longOthers, "volume=0.1")
    longMsg  := f_join(longOthers)
    log.info(longMsg)
    strategy.entry("Achat", strategy.long, qty=0.1, alert_message = longMsg)

if sellSignal
    var string shortMsg = ""
    shortOthers = array.new_string()
    array.push(shortOthers, "magic=" + str.tostring(magic_ea))
    array.push(shortOthers, "key=" + key_ea)
    array.push(shortOthers, "symbol=" + pc_symbol)
    array.push(shortOthers, "order_type=sell")
    array.push(shortOthers, "volume=0.1")
    shortMsg := f_join(shortOthers)
    log.info(shortMsg)
    strategy.entry("Vente", strategy.short, qty=0.1, alert_message = "")
